DOCSP-46021 - v8.2.1 Release
mongodb/docs-entity-framework pull request #44
Opened 2024-12-13 00:53 UTC by mongoKart

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-node/blob/master/REVIEWING.md)

JIRA - https://jira.mongodb.org/browse/DOCSP-46021
Staging - 

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Are all the links working?
- [x] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-12-14 00:39 UTC, stephmarie17 approved these changes
LGTM

2024-12-16 12:28 UTC, damieng requested changes
Just one clarification but otherwise LGTM

2024-12-16 18:29 UTC, mongoKart commented on source/whats-new.txt
> +- Adds support for creating indexes on one or more properties when you call the
Is the use expected to call the `CreateIndex()` method, or do they just have to call `HasIndex()` like you showed in [your example?](https://github.com/mongodb/mongo-efcore-provider/pull/163) I want to make sure I get the details right.

2024-12-16 20:02 UTC, damieng commented on source/whats-new.txt
> +- Adds support for creating indexes on one or more properties when you call the
Sorry, yes, HasIndex.

2024-12-17 16:41 UTC, damieng commented on source/whats-new.txt
> +     var result = client.CreateDatabase(context.GetService<IDesignTimeModel>());
Let's replace this last line with `context.Database.EnsureCreated();`

2024-12-17 16:45 UTC, stephmarie17 approved these changes
LGTM from the docs writing side

2024-12-17 17:30 UTC, merged